# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='treated',
            new_name='created',
        ),
    ]
