# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.FileField(null=True, upload_to=b'/static//img/'),
        ),
    ]
