# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160218_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(null=True, upload_to=b'/static//img/'),
        ),
    ]
