# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160218_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='img',
        ),
    ]
