# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='image',
            new_name='title_image',
        ),
    ]
