# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 05:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
        ('blog', '0014_auto_20160304_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='filer.Image'),
        ),
    ]
