# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 06:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_entry_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='logo',
        ),
        migrations.AlterField(
            model_name='article_image',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
