# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160304_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_image',
            name='image',
            field=models.ImageField(null=True, upload_to=b'/media/img/'),
        ),
    ]
